id = "fluent"
name = "Fluent Translation List"
version = "0.0.1"
schema_version = 1
authors = ["beerpsi <beerpsi@duck.com>"]
description = "FTL language support."
repository = "https://github.com/beer-psi/zed-fluent"

[grammars.fluent]
repository = "https://github.com/beerpsi-forks/tree-sitter-fluent"
rev = "b079d7c78966589e7f84ee6e60afb342579cc3ba"
