id = "fluent"
name = "Fluent Translation List"
version = "0.0.2"
schema_version = 1
authors = ["beerpsi <beerpsi@duck.com>"]
description = "FTL language support."
repository = "https://github.com/beer-psi/zed-fluent"

[grammars.fluent]
repository = "https://github.com/beerpsi-forks/tree-sitter-fluent"
rev = "c00bc7392c594300b1ef075a3d58f1d1122b90f7"
